--activators
require('ss20.activators.practiceDummy')
require('ss20.activators.alchemyStation')
require('ss20.activators.staffStation')
require('ss20.activators.teleportPad')
require('ss20.activators.repair')
require('ss20.soulBottle')
require('ss20.placement')
require('ss20.rooms')
require('ss20.spell')
require('ss20.tooltip')
require('ss20.teleport')
require('ss20.soulShop')
require('ss20.stones')
require('ss20.explodeWall')
--MCM MENU--------------------------------------------------
require('ss20.mcm')
