name: Package mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: "mod"

    - name: Package mod
      run: |
        cd mod
        unzip assets.zip -d "Data Files"
        cp mod.esp "Data Files/MMM2020_1.esp"

    - name: Publish mod
      uses: actions/upload-artifact@v2
      with:
        name: MMM2020_1
        path: "mod/Data Files"
