name: Package mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: "mod"

    - name: Package mod
      run: |
        cd mod
        cp assets.zip mod.zip
        mv mod.esp MMM2020_1.esp
        zip mod.zip MMM2020_1.esp
        pushd "Data Files"
        zip -r ../mod.zip .
        popd

    - name: Publish mod
      uses: actions/upload-artifact@v2
      with:
        name: MMM2020_1
        path: mod/mod.zip
